[package]
name = "dts-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.8"
derive_more = "0.99"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "ast_parser"
harness = false
